### ISSUE TITLE
the problem with `screen` and `tmux`

### ISSUE THREAD

**Issue by AryanGh1379** [kdav5758/MiniPrompt#1]
so I had this problem with tmux and screen:
https://asciinema.org/a/zEdjTiNDx1b6FHyFeDAewV1eL
and here:
https://paste.ubuntu.com/p/MgnMfFxTFH/
https://i.imgur.com/qcr2hsN.png
I found out what the problem is (line 309), so I removed the `';' `character on line 309, and `screen` is working just fine. but the problem with `tmux` still exists.

**Comment by kdav5758** [comment]
Hello there!
I was looking into your problem and it's kind of confusing. On the latest version of MiniPrompt (dev branch basically) I didn't experience the issues you were saying. I ran both `tmux` and `screen` with latest MiniPrompt stable and testing releases, on `st`, `Kitty Terminal`, `Alacritty` and `Gnome Terminal` and in none of them the issues appeared. Here is an example with Kitty Terminal:

<img
  src="https://i.imgur.com/APuXsgF.gif"
  alt="MiniPrompt with Kitty Terminal and a custom theme"
  width="55%"
  align="center"
  style="border-radius:2%"
/>

Could you please specify which release you are using? that way I can test it on it and see if it is a bug of that release.

Furtheremore, the solution your specified for `screen` (removing `;` from line 309) actually broke both `tmux` and `screen` in my case, so maybe you should consider putting that back there.

**So, my recommendations?**
-  Do a clean install of the latest stable release and, of course, update your .bashrc with the one in the repo's `main` branch. Of course, before the clean install, you must delete the prompt it self:
```bash
# delere recursively the directory
$ sudo -rfv /usr/local/bin/MiniPrompt*
```
- Install latest version of both `tmux` and `screen`
-  Check your `tmux` and `screen` configs
- Check your `.bashrc` and see if there is anything that shouldn't be there that might be part of your **own** configuration.
